services:
  - type: web
    name: auto-project
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: VITE_APP_VERSION
        from:
          type: git
          name: commit
          property: short_sha