export const GameConfig = {
    MAX_CLIENTS: 2,
    MAX_TURN: 10,
    MAX_ROUND: 5,
    PLAYER_MAX_HP: 100,
    PLAYER_MAX_MP: 50,
    PLAYER_MAX_SHIELD: 100,
    PLAYER_RATIO_HP: 100,
    PLAYER_RATIO_MP: 100,
    TURN_START: 'turn_end',
    TURN_END: 'turn_end',
    ROUND_START: 'round_start',
    ROUND_END: 'round_end',
    SPECIFIC_TURN_START: 'specific_turn_Start',
    SPECIFIC_TURN_END: 'specific_turn_End',
};
